# Generated by Django 6.0.3 on 2026-03-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='end_by',
        ),
    ]
