# Generated by Django 6.0.3 on 2026-03-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0002_remove_todolist_end_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
