# Generated by Django 6.0.3 on 2026-03-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0003_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
